---
- hosts: localhost
  connection: local
  gather_facts: False
  vars:
    keypair: test
    instance_type: t2.micro
    image: "ami-079b5e5b3971bd10d"
    region: ap-south-1
    user_access_key: "xxxxxxxxxxxxxxxxxxxxx"
    user_secret_key: "xxxxxxxxxxxxxxxxxxxxx"

  tasks:
    - name: startup new instance
      ec2:
         key_name: "{{ keypair }}"
         group_id : "sg-037689543a6aff3bc"
         instance_type: "{{ instance_type }}"
         image: "{{ image }}"
         wait: true
         count: 1
         region: "{{ region }}"
         assign_public_ip: yes
         vpc_subnet_id: "subnet-00e9d97d372e1cd0b"
         aws_access_key: "{{ user_access_key }}"
         aws_secret_key: "{{ user_secret_key }}"
      register: ec2

    - debug:
        var: ec2.instances[0].public_ip
